version: "3.6"

services:
  app-mainnet:
    build:
      context: .
      args:
        FLASK_ENV: production
    container_name: 'api-coin-market-cap'
    ports:
      - 5003:5000
    volumes:
      - ./:/app
    env_file:
      - .env.mainnet
    environment:
      FLASK_ENV: production
      FLASK_APP: app.py  # Update with the path to your main app module
    depends_on:
      - rediscmc
    restart: unless-stopped

  rediscmc:
    image: redis
    container_name: 'redis-coin-market-cap'
    ports:
      - 6381:6379
    volumes:
      - redis_data:/data
    restart: unless-stopped


volumes:
  redis_data: